default:
  just --list

clean:
  @scala-cli clean .

build:
  @scala-cli compile .

run year day:
  @scala-cli run . --main-class solutions.y{{year}}.day{{day}}.run

runp year day part:
  @scala-cli run . --main-class solutions.y{{year}}.day{{day}}.run -- --part {{part}}

repl:
  @scala-cli repl .

test:
  @scala-cli test .

create year day:
  @scala-cli run . --main-class create -- --year {{year}} --day {{day}}

download year day:
  @scala-cli run . --main-class download -- --year {{year}} --day {{day}}
